{% set name = "applicationinsights" %}
{% set version = "0.11.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b761f3ef0680acf4731906dfc1807faa6f2a57168ae74592db0084a6099f7b3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - applicationinsights
    - applicationinsights.channel
    - applicationinsights.channel.contracts
    - applicationinsights.django
    - applicationinsights.exceptions
    - applicationinsights.flask
    - applicationinsights.logging
    - applicationinsights.requests
  requires:
    - django

about:
  home: https://github.com/Microsoft/ApplicationInsights-Python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: This project extends the Application Insights API surface to support Python.

  description: |
    Application Insights is a service that allows developers to keep their application available,
    performing and succeeding. This Python module will allow you to send telemetry of various kinds
    (event, trace, exception, etc.) to the Application Insights service where they can be visualized
    in the Azure Portal.
  doc_url: https://microsoft.github.io/ApplicationInsights-Python/
  dev_url: https://github.com/Microsoft/ApplicationInsights-Python

extra:
  recipe-maintainers:
    - andreyz4k
